---
# tasks file for wordpress

name: install wordpress
hosts: all
become: true
become_method: sudo
user: centos
- name: install dependencies
  package:
    name:
      - httpd 
      - mariadb 
      - mariadb-server 
      - php 
      - php-server
      - wget 
    state: installed

- name: create wordpress dir
  file:
    path: "/var/www/html/{{ beckinc.org }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755

- name: get wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html/{{ beckinc.org }}
    extra_opts: --strip=1
    remote_src: yes
    owner: apache
    group: apache
  notify: get API information

- name: start mariadb
  service:
    name: mariadb
    state: started
    enabled: true


- name: start httpd
  service:
    name: httpd
    state: started
    enabled: true
