---
- name: Install wordpress on CentOS 7 
  # gather_facts: no 
  hosts: 54.149.227.242   
  become: true
  become_method: sudo
  user: centos  
  tasks: 
    - name:
      shell: "yum -y install epel-release"

    - name: 
      shell: "yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y"  

    - name:
      shell: "yum-config-manager --enable remi-php72"

    - name:
      shell: "yum update -y"   



    - name: Install httpd
      package: 
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - php
        - mariadb-server
        - mysql
        - elinks
        - php-mysql
        - php-gd 
      ignore_errors: yes 

    

    - name: Download wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz 
        dest: /home/centos/

    - name: add users
      user: 
        name: "{{ item }}"
        state: present
      with_items:
        - bob
        - ben
        - lisa
        - katty      

    - name: Unzip wordpress
      unarchive: 
        src: ~/wordpress-5.4.tar.gz
        dest: /var/www/html/
        remote_src: yes 

    - name: move files
      shell: "mv /var/www/html/wordpress/*  /var/www/html/"
      ignore_errors: yes 

    - name: Move index.html 
      shell: "mv /var/www/html/index.html /tmp/"
      ignore_errors: true

    - name: run apache 
      systemd: 
        name: httpd 
        state: restarted 
        enabled: yes 
      ignore_errors: yes 
