- name: add a record to route53
  hosts: localhost
  gather_facts: false
    - route53:
      command: create
      zone: beckinc.org
      record: beckinc.org
      type: A
      ttl: 7200
      value: 35.163.121.52
      wait: yes