- name: add an inbound rule for security group
  hosts: localhost
  gather_facts: false
  tasks:
  - name: example2 ec2 group
    ec2_group:
      name:
      vpc_id: 12345
      region: eu-west-1
      rules:
        # 'ports' rule keyword was introduced in version 2.4. It accepts a single port value or a list of values including ranges (from_port-to_port).
        - proto: tcp
          ports: 22
          group_name: example-vpn
        - proto: tcp
          ports:
            - 1167
          cidr_ip: 0.0.0.0/0